// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261003112435_a")]
    partial class a
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bánh kẹo & Đồ ăn vặt",
                            Description = "Snack, bánh quy, kẹo dẻo, hạt khô"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Nước giải khát & Trà",
                            Description = "Nước ngọt, nước khoáng, trà đóng chai"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sữa & Sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa chua, phô mai, bơ"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Mì gói & Thực phẩm ăn liền",
                            Description = "Mì ăn liền, phở khô, cháo gói, hủ tiếu"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị & Dầu ăn",
                            Description = "Nước mắm, hạt nêm, dầu thực vật, nước tương"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Đồ đóng hộp & Chế biến sẵn",
                            Description = "Cá hộp, thịt hộp, xúc xích, pate"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Gạo & Các loại ngũ cốc",
                            Description = "Gạo tẻ, gạo nếp, đậu xanh, yến mạch"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Thực phẩm tươi sống",
                            Description = "Thịt heo, thịt bò, gia cầm, hải sản, trứng"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Rau củ & Trái cây tươi",
                            Description = "Rau xanh, củ quả, trái cây theo mùa"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Thực phẩm đông lạnh",
                            Description = "Cá viên, bò viên, chả giò, bánh bao đông lạnh"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Kem & Đồ lạnh",
                            Description = "Kem cây, kem hộp, đá viên đóng túi"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Cà phê & Nước tăng lực",
                            Description = "Cà phê hòa tan, cà phê lon, nước tăng lực"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Bia & Đồ uống có cồn",
                            Description = "Bia lon, rượu vang, nước trái cây lên men"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Chăm sóc cá nhân",
                            Description = "Sữa tắm, dầu gội, kem đánh răng, xà phòng"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Mỹ phẩm & Dưỡng da",
                            Description = "Sữa rửa mặt, kem chống nắng, tẩy trang, mặt nạ"
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "Chăm sóc nhà cửa",
                            Description = "Nước rửa chén, nước lau nhà, nước giặt, xả vải"
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "Giấy & Màng bọc",
                            Description = "Giấy vệ sinh, khăn giấy ăn, màng bọc thực phẩm, túi zip"
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "Dụng cụ vệ sinh & Rác",
                            Description = "Bàn chải, khăn lau, túi đựng rác, miếng rửa bát"
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "Đồ dùng gia đình & Bếp",
                            Description = "Nồi chảo, hộp đựng thực phẩm, ly nhựa, đũa muỗng"
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "Văn phòng phẩm",
                            Description = "Bút viết, tập học sinh, băng keo, kéo, kẹp giấy"
                        },
                        new
                        {
                            CategoryId = 21,
                            CategoryName = "Mẹ & Bé",
                            Description = "Tã bỉm, sữa bột, ăn dầm, khăn ướt em bé"
                        },
                        new
                        {
                            CategoryId = 22,
                            CategoryName = "Chăm sóc thú cưng",
                            Description = "Thức ăn cho chó mèo, cát vệ sinh, phụ kiện"
                        },
                        new
                        {
                            CategoryId = 23,
                            CategoryName = "Đồ dùng cá nhân & Phụ kiện",
                            Description = "Khẩu trang, áo mưa, ô dù, pin gia dụng"
                        },
                        new
                        {
                            CategoryId = 24,
                            CategoryName = "Bánh mì & Bánh tươi",
                            Description = "Bánh mì sandwich, bánh ngọt tươi, bánh bao nóng"
                        },
                        new
                        {
                            CategoryId = 25,
                            CategoryName = "Sản phẩm y tế cơ bản",
                            Description = "Băng cá nhân, nước muối sinh lý, dán hạ sốt, cồn y tế"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chuẩn");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "12 Lê Lợi, Q.1, TP.HCM",
                            CustomerName = "Nguyễn Văn An",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901234567",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "45 Nguyễn Trãi, Q.5, TP.HCM",
                            CustomerName = "Trần Thị Bình",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912345678",
                            RewardPoints = 40
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "78 CMT8, Q.3, TP.HCM",
                            CustomerName = "Lê Hoàng Cường",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0987654321",
                            RewardPoints = 0
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "23 Hai Bà Trưng, Q.1, TP.HCM",
                            CustomerName = "Phạm Minh Đức",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0901122334",
                            RewardPoints = 85
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "56 Phan Văn Trị, Q.5, TP.HCM",
                            CustomerName = "Võ Thị Hạnh",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0912233445",
                            RewardPoints = 210
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "89 Điện Biên Phủ, Q. Bình Thạnh, TP.HCM",
                            CustomerName = "Đặng Quốc Huy",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 25
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "34 Võ Văn Tần, Q.3, TP.HCM",
                            CustomerName = "Bùi Ngọc Lan",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0904455667",
                            RewardPoints = 120
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "67 Lý Thường Kiệt, Q.10, TP.HCM",
                            CustomerName = "Huỳnh Thanh Nam",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0915566778",
                            RewardPoints = 60
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "91 Nguyễn Văn Cừ, Q.5, TP.HCM",
                            CustomerName = "Ngô Thị Mai",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0986677889",
                            RewardPoints = 15
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "15 Trường Chinh, Q. Tân Bình, TP.HCM",
                            CustomerName = "Đỗ Minh Quân",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0907788990",
                            RewardPoints = 175
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "42 Nguyễn Đình Chiểu, Q.3, TP.HCM",
                            CustomerName = "Phan Thị Thảo",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918899001",
                            RewardPoints = 95
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "76 Cộng Hòa, Q. Tân Bình, TP.HCM",
                            CustomerName = "Trương Hoàng Long",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0989900112",
                            RewardPoints = 5
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "28 Nam Kỳ Khởi Nghĩa, Q.1, TP.HCM",
                            CustomerName = "Lý Mỹ Linh",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901011223",
                            RewardPoints = 250
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "53 Hoàng Văn Thụ, Q. Phú Nhuận, TP.HCM",
                            CustomerName = "Mai Văn Khoa",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912122334",
                            RewardPoints = 70
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "84 Nguyễn Kiệm, Q. Gò Vấp, TP.HCM",
                            CustomerName = "Nguyễn Thị Yến",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983233445",
                            RewardPoints = 35
                        },
                        new
                        {
                            CustomerId = 16,
                            Address = "19 Xô Viết Nghệ Tĩnh, Q. Bình Thạnh, TP.HCM",
                            CustomerName = "Phạm Tuấn Anh",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0904344556",
                            RewardPoints = 135
                        },
                        new
                        {
                            CustomerId = 17,
                            Address = "62 Nguyễn Oanh, Q. Gò Vấp, TP.HCM",
                            CustomerName = "Trần Ngọc Diệp",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0915455667",
                            RewardPoints = 55
                        },
                        new
                        {
                            CustomerId = 18,
                            Address = "37 Lạc Long Quân, Q.11, TP.HCM",
                            CustomerName = "Lê Minh Tâm",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0986566778",
                            RewardPoints = 10
                        },
                        new
                        {
                            CustomerId = 19,
                            Address = "48 Nguyễn Thị Minh Khai, Q.1, TP.HCM",
                            CustomerName = "Võ Quốc Thắng",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0907677889",
                            RewardPoints = 190
                        },
                        new
                        {
                            CustomerId = 20,
                            Address = "72 Tô Hiến Thành, Q.10, TP.HCM",
                            CustomerName = "Đặng Thị Kim",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918788990",
                            RewardPoints = 80
                        },
                        new
                        {
                            CustomerId = 21,
                            Address = "16 Quang Trung, Q. Gò Vấp, TP.HCM",
                            CustomerName = "Bùi Thanh Tùng",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0989899001",
                            RewardPoints = 20
                        },
                        new
                        {
                            CustomerId = 22,
                            Address = "39 Pasteur, Q.1, TP.HCM",
                            CustomerName = "Huỳnh Ngọc Anh",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0900900112",
                            RewardPoints = 160
                        },
                        new
                        {
                            CustomerId = 23,
                            Address = "55 Lê Văn Sỹ, Q.3, TP.HCM",
                            CustomerName = "Ngô Minh Châu",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0911011223",
                            RewardPoints = 45
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
