// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20260926123009_NguyenLeChiCong_212410094")]
    partial class NguyenLeChiCong_212410094
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bánh kẹo & Đồ ăn vặt",
                            Description = "Snack, bánh quy, kẹo dẻo, hạt khô"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Nước giải khát & Trà",
                            Description = "Nước ngọt, nước khoáng, trà đóng chai"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sữa & Sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa chua, phô mai, bơ"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Mì gói & Thực phẩm ăn liền",
                            Description = "Mì ăn liền, phở khô, cháo gói, hủ tiếu"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị & Dầu ăn",
                            Description = "Nước mắm, hạt nêm, dầu thực vật, nước tương"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Đồ đóng hộp & Chế biến sẵn",
                            Description = "Cá hộp, thịt hộp, xúc xích, pate"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Gạo & Các loại ngũ cốc",
                            Description = "Gạo tẻ, gạo nếp, đậu xanh, yến mạch"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Thực phẩm tươi sống",
                            Description = "Thịt heo, thịt bò, gia cầm, hải sản, trứng"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Rau củ & Trái cây tươi",
                            Description = "Rau xanh, củ quả, trái cây theo mùa"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Thực phẩm đông lạnh",
                            Description = "Cá viên, bò viên, chả giò, bánh bao đông lạnh"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Kem & Đồ lạnh",
                            Description = "Kem cây, kem hộp, đá viên đóng túi"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Cà phê & Nước tăng lực",
                            Description = "Cà phê hòa tan, cà phê lon, nước tăng lực"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Bia & Đồ uống có cồn",
                            Description = "Bia lon, rượu vang, nước trái cây lên men"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Chăm sóc cá nhân",
                            Description = "Sữa tắm, dầu gội, kem đánh răng, xà phòng"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Mỹ phẩm & Dưỡng da",
                            Description = "Sữa rửa mặt, kem chống nắng, tẩy trang, mặt nạ"
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "Chăm sóc nhà cửa",
                            Description = "Nước rửa chén, nước lau nhà, nước giặt, xả vải"
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "Giấy & Màng bọc",
                            Description = "Giấy vệ sinh, khăn giấy ăn, màng bọc thực phẩm, túi zip"
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "Dụng cụ vệ sinh & Rác",
                            Description = "Bàn chải, khăn lau, túi đựng rác, miếng rửa bát"
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "Đồ dùng gia đình & Bếp",
                            Description = "Nồi chảo, hộp đựng thực phẩm, ly nhựa, đũa muỗng"
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "Văn phòng phẩm",
                            Description = "Bút viết, tập học sinh, băng keo, kéo, kẹp giấy"
                        },
                        new
                        {
                            CategoryId = 21,
                            CategoryName = "Mẹ & Bé",
                            Description = "Tã bỉm, sữa bột, ăn dầm, khăn ướt em bé"
                        },
                        new
                        {
                            CategoryId = 22,
                            CategoryName = "Chăm sóc thú cưng",
                            Description = "Thức ăn cho chó mèo, cát vệ sinh, phụ kiện"
                        },
                        new
                        {
                            CategoryId = 23,
                            CategoryName = "Đồ dùng cá nhân & Phụ kiện",
                            Description = "Khẩu trang, áo mưa, ô dù, pin gia dụng"
                        },
                        new
                        {
                            CategoryId = 24,
                            CategoryName = "Bánh mì & Bánh tươi",
                            Description = "Bánh mì sandwich, bánh ngọt tươi, bánh bao nóng"
                        },
                        new
                        {
                            CategoryId = 25,
                            CategoryName = "Sản phẩm y tế cơ bản",
                            Description = "Băng cá nhân, nước muối sinh lý, dán hạ sốt, cồn y tế"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
