// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261003113935_q")]
    partial class q
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bánh quy tuổi thơ",
                            Description = "Các loại bánh quy quen thuộc gắn liền với tuổi thơ"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Snack",
                            Description = "Snack khoai tây, snack bắp và các loại snack giòn"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Kẹo",
                            Description = "Kẹo dẻo, kẹo cứng và các loại kẹo tuổi thơ"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Bánh xốp",
                            Description = "Bánh xốp phủ kem và bánh xốp nhiều hương vị"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Bánh que",
                            Description = "Các loại bánh que và bánh que phủ socola"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Bánh gạo",
                            Description = "Bánh gạo giòn và các sản phẩm từ gạo"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Bắp rang",
                            Description = "Bắp rang bơ và bắp rang nhiều hương vị"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Khô & Đồ sấy",
                            Description = "Cá khô, bò khô, trái cây sấy và đồ ăn khô"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Rong biển",
                            Description = "Rong biển ăn liền và snack rong biển"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Đậu phộng & Hạt",
                            Description = "Đậu phộng, hạt hướng dương và các loại hạt"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Mì ăn liền",
                            Description = "Mì gói và mì ly ăn liền"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Xúc xích",
                            Description = "Xúc xích ăn liền và xúc xích tiệt trùng"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Cá viên & Đồ chiên",
                            Description = "Các món ăn vặt chế biến sẵn"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Bánh mì",
                            Description = "Bánh mì sandwich và bánh mì ăn sáng"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Bánh ngọt",
                            Description = "Bánh bông lan, bánh kem và bánh ngọt"
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "Socola",
                            Description = "Socola thanh, socola viên và kẹo socola"
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "Kem",
                            Description = "Kem cây và kem hộp"
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "Nước ngọt",
                            Description = "Coca Cola, Pepsi, 7Up và các loại nước ngọt"
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "Trà đóng chai",
                            Description = "Trà xanh, trà đào và trà trái cây"
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "Nước trái cây",
                            Description = "Nước cam, nước táo và các loại nước trái cây"
                        },
                        new
                        {
                            CategoryId = 21,
                            CategoryName = "Sữa",
                            Description = "Sữa hộp và các sản phẩm từ sữa"
                        },
                        new
                        {
                            CategoryId = 22,
                            CategoryName = "Nước tăng lực",
                            Description = "Các loại nước tăng lực"
                        },
                        new
                        {
                            CategoryId = 23,
                            CategoryName = "Combo Snack Box",
                            Description = "Combo nhiều món ăn vặt dành cho khách hàng"
                        },
                        new
                        {
                            CategoryId = 24,
                            CategoryName = "Đồ ăn vặt tuổi thơ",
                            Description = "Các món ăn vặt quen thuộc của thế hệ 8x, 9x"
                        },
                        new
                        {
                            CategoryId = 25,
                            CategoryName = "Sản phẩm đặc biệt",
                            Description = "Các sản phẩm mới và sản phẩm bán theo mùa"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chuẩn");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "893100100001",
                            CategoryId = 1,
                            Price = 18000m,
                            ProductName = "Bánh Oreo vị socola 133g",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "893100100002",
                            CategoryId = 1,
                            Price = 35000m,
                            ProductName = "Bánh quy Cosy Marie 300g",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "893100100003",
                            CategoryId = 2,
                            Price = 15000m,
                            ProductName = "Snack khoai tây Lays 68g",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "893100100004",
                            CategoryId = 2,
                            Price = 12000m,
                            ProductName = "Snack Oishi tôm cay 75g",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "893100100005",
                            CategoryId = 3,
                            Price = 10000m,
                            ProductName = "Kẹo dẻo Chupa Chups",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "893100100006",
                            CategoryId = 3,
                            Price = 8000m,
                            ProductName = "Kẹo Dynamite vị bạc hà",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "893100100007",
                            CategoryId = 4,
                            Price = 12000m,
                            ProductName = "Bánh xốp kem socola",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "893100100008",
                            CategoryId = 4,
                            Price = 12000m,
                            ProductName = "Bánh xốp kem dâu",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "893100100009",
                            CategoryId = 5,
                            Price = 15000m,
                            ProductName = "Bánh que socola",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "893100100010",
                            CategoryId = 5,
                            Price = 15000m,
                            ProductName = "Bánh que phô mai",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "893100100011",
                            CategoryId = 6,
                            Price = 18000m,
                            ProductName = "Bánh gạo One One vị ngọt",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "893100100012",
                            CategoryId = 6,
                            Price = 20000m,
                            ProductName = "Bánh gạo cay",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "893100100013",
                            CategoryId = 7,
                            Price = 25000m,
                            ProductName = "Bắp rang bơ",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "893100100014",
                            CategoryId = 7,
                            Price = 28000m,
                            ProductName = "Bắp rang caramel",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "893100100015",
                            CategoryId = 8,
                            Price = 45000m,
                            ProductName = "Khô bò sợi 50g",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 16,
                            Barcode = "893100100016",
                            CategoryId = 8,
                            Price = 35000m,
                            ProductName = "Xoài sấy dẻo 100g",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 17,
                            Barcode = "893100100017",
                            CategoryId = 9,
                            Price = 25000m,
                            ProductName = "Rong biển ăn liền Tao Kae Noi",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 18,
                            Barcode = "893100100018",
                            CategoryId = 9,
                            Price = 18000m,
                            ProductName = "Snack rong biển vị truyền thống",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 19,
                            Barcode = "893100100019",
                            CategoryId = 10,
                            Price = 20000m,
                            ProductName = "Đậu phộng da cá 100g",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 20,
                            Barcode = "893100100020",
                            CategoryId = 10,
                            Price = 15000m,
                            ProductName = "Hạt hướng dương vị truyền thống",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 21,
                            Barcode = "893100100021",
                            CategoryId = 11,
                            Price = 5000m,
                            ProductName = "Mì Hảo Hảo tôm chua cay",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 22,
                            Barcode = "893100100022",
                            CategoryId = 11,
                            Price = 10000m,
                            ProductName = "Mì Omachi sườn hầm ngũ quả",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 23,
                            Barcode = "893100100023",
                            CategoryId = 12,
                            Price = 32000m,
                            ProductName = "Xúc xích tiệt trùng Vissan",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 24,
                            Barcode = "893100100024",
                            CategoryId = 12,
                            Price = 35000m,
                            ProductName = "Xúc xích phô mai",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 25,
                            Barcode = "893100100025",
                            CategoryId = 13,
                            Price = 45000m,
                            ProductName = "Cá viên chiên 500g",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 26,
                            Barcode = "893100100026",
                            CategoryId = 13,
                            Price = 55000m,
                            ProductName = "Bò viên 500g",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 27,
                            Barcode = "893100100027",
                            CategoryId = 14,
                            Price = 28000m,
                            ProductName = "Bánh mì sandwich 400g",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 28,
                            Barcode = "893100100028",
                            CategoryId = 14,
                            Price = 15000m,
                            ProductName = "Bánh mì ngọt nhân kem",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 29,
                            Barcode = "893100100029",
                            CategoryId = 15,
                            Price = 45000m,
                            ProductName = "Bánh bông lan kem 300g",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 30,
                            Barcode = "893100100030",
                            CategoryId = 15,
                            Price = 30000m,
                            ProductName = "Bánh bông lan cuộn",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 31,
                            Barcode = "893100100031",
                            CategoryId = 16,
                            Price = 25000m,
                            ProductName = "Socola thanh KitKat",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 32,
                            Barcode = "893100100032",
                            CategoryId = 16,
                            Price = 35000m,
                            ProductName = "Socola thanh Hershey's",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 33,
                            Barcode = "893100100033",
                            CategoryId = 17,
                            Price = 12000m,
                            ProductName = "Kem Merino socola",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 34,
                            Barcode = "893100100034",
                            CategoryId = 17,
                            Price = 15000m,
                            ProductName = "Kem Celano vani",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 35,
                            Barcode = "893100100035",
                            CategoryId = 18,
                            Price = 10000m,
                            ProductName = "Coca Cola lon 330ml",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 36,
                            Barcode = "893100100036",
                            CategoryId = 18,
                            Price = 10000m,
                            ProductName = "Pepsi lon 330ml",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 37,
                            Barcode = "893100100037",
                            CategoryId = 19,
                            Price = 10000m,
                            ProductName = "Trà xanh C2 455ml",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 38,
                            Barcode = "893100100038",
                            CategoryId = 19,
                            Price = 12000m,
                            ProductName = "Trà đào Tea+ 455ml",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 39,
                            Barcode = "893100100039",
                            CategoryId = 20,
                            Price = 12000m,
                            ProductName = "Nước cam Twister 455ml",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 40,
                            Barcode = "893100100040",
                            CategoryId = 20,
                            Price = 12000m,
                            ProductName = "Nước táo 455ml",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 41,
                            Barcode = "893100100041",
                            CategoryId = 21,
                            Price = 8000m,
                            ProductName = "Sữa tươi Vinamilk 180ml",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 42,
                            Barcode = "893100100042",
                            CategoryId = 21,
                            Price = 9000m,
                            ProductName = "Sữa chocolate hộp 180ml",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 43,
                            Barcode = "893100100043",
                            CategoryId = 22,
                            Price = 12000m,
                            ProductName = "Red Bull 250ml",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 44,
                            Barcode = "893100100044",
                            CategoryId = 22,
                            Price = 10000m,
                            ProductName = "Sting dâu 330ml",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 45,
                            Barcode = "893100100045",
                            CategoryId = 23,
                            Price = 50000m,
                            ProductName = "Combo Snack Box Mini",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 46,
                            Barcode = "893100100046",
                            CategoryId = 23,
                            Price = 100000m,
                            ProductName = "Combo Snack Box Tuổi Thơ",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 47,
                            Barcode = "893100100047",
                            CategoryId = 24,
                            Price = 5000m,
                            ProductName = "Kẹo kéo tuổi thơ",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 48,
                            Barcode = "893100100048",
                            CategoryId = 24,
                            Price = 10000m,
                            ProductName = "Bánh đồng tiền tuổi thơ",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 49,
                            Barcode = "893100100049",
                            CategoryId = 25,
                            Price = 150000m,
                            ProductName = "Hộp quà Snack Box đặc biệt",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductId = 50,
                            Barcode = "893100100050",
                            CategoryId = 25,
                            Price = 200000m,
                            ProductName = "Combo Party Snack Box",
                            StockQuantity = 15
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
